jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-lts-11:
        BUILD: stack
        ARGS: "--resolver lts-11"
      stack-lts-12:
        BUILD: stack
        ARGS: "--resolver lts-12"
      stack-lts-14:
        BUILD: stack
        ARGS: "--resolver lts-14"
      stack-network3:
        BUILD: stack
        ARGS: "--stack-yaml stack-network3.yaml"
      stack-nightly:
        BUILD: stack
        ARGS: "--stack-yaml stack-nightly.yaml --resolver nightly"
    maxParallel: 6
  steps:
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      export PATH=$HOME/.local/bin:$PATH
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Build and test'
